/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulariofinogestionbodega;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
/**
 *
 * @author Sebastian
 */
public class NewJFrameBodega extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameBodega
     */
    public NewJFrameBodega() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Registro1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InicioSesion = new javax.swing.JButton();
        BotonRegistro = new javax.swing.JButton();
        registrocontraseña = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fondoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1039, 62, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("BIENVENIDO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 250, 50));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel2.setText("Es hora de gestionar tu bodega ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 370, 30));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("RESGISTRATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 280, 50));

        Registro1.setBackground(new java.awt.Color(255, 255, 0));
        Registro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registro1ActionPerformed(evt);
            }
        });
        getContentPane().add(Registro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 320, 20));

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese nombre de usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 250, 30));

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel5.setText("Ingrese contraseña");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 190, 30));

        InicioSesion.setText("Iniciar sesion");
        InicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioSesionActionPerformed(evt);
            }
        });
        getContentPane().add(InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 100, 30));

        BotonRegistro.setText("Registro");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 100, 30));

        registrocontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrocontraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(registrocontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 320, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("O");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel6.setText("Ingrese contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 190, 30));

        fondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ed334e16fa46ddc7efef88512c3e2ec6_t.jpeg"))); // NOI18N
        getContentPane().add(fondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 620, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Registro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registro1ActionPerformed

    private void InicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioSesionActionPerformed
      Pantalla2 newframe = new Pantalla2();    
      newframe.setVisible(true);
      this.dispose();
        
    }//GEN-LAST:event_InicioSesionActionPerformed

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed

   String usuario = Registro1.getText().trim();
    String contraseña = new String(registrocontraseña.getPassword()).trim();

    if (usuario.isEmpty() || contraseña.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe llenar ambos campos", "Campo vacío", JOptionPane.WARNING_MESSAGE);
    } else {
        guardarUsuario(usuario, contraseña);
        JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        
        Registro1.setText("");
        registrocontraseña.setText("");
    }
} 

    private void guardarUsuario(String usuario, String contraseña) {
    try {
        FileWriter fw = new FileWriter("usuarios_ejemplo.txt", true);
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write(usuario + "," + contraseña);
        bw.newLine();
        bw.close();
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void registrocontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrocontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrocontraseñaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JButton InicioSesion;
    private javax.swing.JTextField Registro1;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField registrocontraseña;
    // End of variables declaration//GEN-END:variables
}
