/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulariofinogestionbodega;

/**
 *
 * @author marco
 */
public class Pantalla5GestionBodegas extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla5GestionBodegas
     */
    public Pantalla5GestionBodegas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        botonP1Ingreso = new javax.swing.JButton();
        botonP2Ver = new javax.swing.JButton();
        botonP3Actualizar = new javax.swing.JButton();
        botonP4Eliminar = new javax.swing.JButton();
        botonP5Consultar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setText("\"Menú Principal - Gestión de Bodega\"");

        botonP1Ingreso.setText("\"Ingresar Producto\"");
        botonP1Ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonP1IngresoActionPerformed(evt);
            }
        });

        botonP2Ver.setText("\"Ver Inventario\"\t");
        botonP2Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonP2VerActionPerformed(evt);
            }
        });

        botonP3Actualizar.setText("\"Actualizar Producto\"");
        botonP3Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonP3ActualizarActionPerformed(evt);
            }
        });

        botonP4Eliminar.setText("\"Eliminar Producto\"\t");
        botonP4Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonP4EliminarActionPerformed(evt);
            }
        });

        botonP5Consultar.setText("\"Consultar Producto\"\t");
        botonP5Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonP5ConsultarActionPerformed(evt);
            }
        });

        botonSalir.setText("\"Salir\"\t");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botonP4Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonP3Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonP1Ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonP2Ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonP5Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonSalir)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(labelTitulo)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(botonP1Ingreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonP2Ver)
                .addGap(18, 18, 18)
                .addComponent(botonP3Actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonP4Eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonP5Consultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonP3ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonP3ActualizarActionPerformed
        new PantallaP3ActualizarProducto().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonP3ActualizarActionPerformed

    private void botonP1IngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonP1IngresoActionPerformed
        new PantallaP1IngresoProducto().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonP1IngresoActionPerformed

    private void botonP2VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonP2VerActionPerformed
        new PantallaP2VerInventario().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonP2VerActionPerformed

    private void botonP4EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonP4EliminarActionPerformed
        new PantallaP4EliminarProducto().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonP4EliminarActionPerformed

    private void botonP5ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonP5ConsultarActionPerformed
        new PantallaP5ConsultarProducto().setVisible(true);
        dispose();
    }//GEN-LAST:event_botonP5ConsultarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        Pantalla3Funciones volver = new Pantalla3Funciones();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla5GestionBodegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla5GestionBodegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla5GestionBodegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla5GestionBodegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla5GestionBodegas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonP1Ingreso;
    private javax.swing.JButton botonP2Ver;
    private javax.swing.JButton botonP3Actualizar;
    private javax.swing.JButton botonP4Eliminar;
    private javax.swing.JButton botonP5Consultar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
